- name: Create Directory UINSTALL/
  file:
    path: "{{c_adx_imnt}}UINSTALL/"
    state: directory

- name: Create Directory ACE3D If Does Not Exist
  file:
    path: "{{c_drive}}ACE3D/"
    state: directory

- name: Download Toshiba Nexus Package ACE From Nexus
  get_url:
    url: "{{nexus_url2}}/repository/tgcs-maven-snapshot/com/toshibacommerce/ace/ACE3D001/{{level_name}}-SNAPSHOT/ACE3D001-{{level_complement}}.zip"
    dest: "{{landing_zone}}"
    timeout: 300

- name: Copy ACE3D
  shell: "cp {{landing_zone}}ACE3D001-{{level_complement}}.zip {{c_drive}}ACE3D/ACE3D001.zip;"

- name: cp unZIp.py and Unziping the packages of installation
  shell: "cp {{landing_zone}}unZIP.PY {{c_adx_imnt}}UINSTALL/;python3 {{c_adx_imnt}}UINSTALL/unZIP.PY 3"
  
- name: cp updFile.py Updating the installation files to automate the installaiton
  shell: "cp {{landing_zone}}updFile.py {{c_adx_imnt}}UINSTALL/; python3 {{c_adx_imnt}}UINSTALL/updFile.py 3"

- name: Copy Files In UINSTALL y ACE3D
  shell: "cp {{landing_zone}}asm.py {{c_adx_imnt}}/; cp {{landing_zone}}AUTO3D.BAT {{c_adx_imnt}};cp {{landing_zone}}START3D.BAT {{c_adx_imnt}}UINSTALL/;"

- name: Printing opc ACE3D
  shell: "echo {{opc}} >> {{c_adx_imnt}}AUTO3D.BAT"

- name: Starting the installation ACE3D
  shell: "{{c_adx_imnt}}UINSTALL/START3D.BAT"

- name: Starting asm and reboot controller...
  shell: "python2 {{c_adx_imnt}}asm.py {{ASM}} AG"
  ignore_errors: true

- name: Wait For Reboot If There Was A Change
  wait_for_connection:
    sleep: 5
    delay: 10
    timeout: 300

- name: Check de log file of ASM
  command: cat adxcshsf.dat
  args:
      chdir: "{{c_adx_sdt1}}"

- name: Cleaning adx_imnt
  shell: "rm -r {{c_adx_imnt}}*"