
- name: Preparing the adx_imnt/ directory.
  include_role:
    name: installation
    tasks_from: Prepare_adx_imnt_Directory.yml

- name: Cheks if there is an tcxpay-common old Version dat
  stat:
    path: "{{c_adx_ipgm}}ADXCETCD.DAT"
  register: lp

- name: Deleting the tcxpay-common old Version dat and Installation
  shell: "rm {{c_adx_ipgm}}ADXCETCD.DAT"
  when: lp.stat.exists

- name: Check adx_imnt scripts Exist
  stat:
    path: "{{c_adx_imnt}}PAYINST.BAT"
  register: imnt_pay

- name: Deleting adx_imnt:PAYINST.BAT
  shell: "rm -f {{c_adx_imnt}}PAYINST.BAT"
  when: imnt_pay.stat.exists

- name: Copying files from Landing zone to adx_imnt
  shell: "cp {{landing_zone}}asm.py {{c_adx_imnt}}"

- name: Download Toshiba Nexus Package TCxPay Common From Nexus
  get_url:
    url: "{{nexus_url2}}/repository/tgcs-maven-release/com/tgcs/tcxpay/tcxpay-common-install/{{level}}/tcxpay-common-install-{{level}}.iso"
    dest: "{{landing_zone}}"
    timeout: 300

- name: Copy the iso to F:/
  shell: "cp {{landing_zone}}tcxpay-common-install-{{level}}.iso {{f_drive}} && echo ISO available in F:/"

- name: Mount ISO Image
  command: "{{run_4690}} isomount f:/adxetc/home/vxuser/Landing/tcxpay-common-install-{{level}}.iso"

- name: Copying PAYINST.BAT from cdrom/ to adx_imnt
  shell: "cp /mnt/cdrom/4690/PAYINST.BAT {{c_adx_imnt}} && echo PAYINST.BAT was copied from cdrom/ to adx_imnt"

- name: Starting installation's scripts
  shell: "{{c_adx_imnt}}PAYINST.BAT SILENT"

- name: Check the adx_imnt/ installation files exist.
  include_role:
    name: installation
    tasks_from: Check_adx_imnt_Files.yml

- name: Deleting the ISO's form landing zone and F:/
  shell: "rm -f {{landing_zone}}tcxpay-common-install-{{level}}.iso; rm -f {{f_drive}}tcxpay-common-install-{{level}}.iso;"

- name: Starting asm and reboot controller...
  shell: "python2 {{c_adx_imnt}}asm.py Accept EC"
  ignore_errors: true
  
- name: Wait For Reboot If There Was A Change
  wait_for_connection:
    sleep: 5
    delay: 10
    timeout: 300

- name: Check de log file of ASM
  command: cat adxcshsf.dat
  args:
      chdir: "{{c_adx_sdt1}}"

- name: Cleaning adx_imnt
  shell: "rm -r {{c_adx_imnt}}*"